# Generated by Django 4.1.3 on 2023-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
