# Generated by Django 4.1.3 on 2023-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="sub_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
